name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      publish-dj-server:
        description: "Generate dj-server image"
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

  publish:
    if: ${{ github.event.inputs.publish-dj-server }}
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v1
