name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      publish-dj-server:
        description: "Generate dj-server image"
        type: boolean
        required: true
        default: true

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'

  build:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Print all files
        run: echo '${{ toJSON(steps.changed-files.outputs) }}'

  publish:
    if: github.event.inputs.publish-dj-server || startsWith(github.ref, 'refs/tags/')  || github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v1
